"""Add drive approval

Revision ID: 2b6b31702e3e
Revises: 30f19b9c5e72
Create Date: 2026-07-15 21:00:00.252490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6b31702e3e'
down_revision = '30f19b9c5e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
